version: '3.7'

services:
  server:
    build : .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    stdin_open: true
    depends_on:
      - server
    ports:
      - "3000:3000"

